from pydantic import BaseModel, Field


class AgentRequest(BaseModel):
    """
    Request for the Coding Agent.
    """

    task: str = Field(
        ...,
        min_length=1,
        max_length=20000,
    )

    temperature: float = Field(
        default=0.2,
        ge=0.0,
        le=2.0,
    )

    max_tokens: int = Field(
        default=2048,
        ge=1,
        le=8192,
    )


class AgentResponse(BaseModel):
    """
    Response generated by the Coding Agent.
    """

    success: bool
    project_id: int
    task: str
    response: str